spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seminar2025?allowPublicKeyRetrieval=true
    username: user
    password: somepassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true

jwt:
  secret: this-is-a-very-long-and-secure-secret-key-for-jwt-token-generation
  expiration-in-ms: 86400000

logging:
  level:
    org:
      springframework:
        data:
          jdbc: DEBUG
        jdbc:
          core:
            JdbcTemplate: DEBUG
            namedparam:
              NamedParameterJdbcTemplate: TRACE

sugang:
  base-url: "https://sugang.snu.ac.kr"
  init-url: "/sugang/co/co010.action"
  ajax-url: "/sugang/cc/cc100ajax.action"
  search-url: "/sugang/cc/cc100InterfaceSrch.action"
  export-url: "/sugang/cc/cc100InterfaceExcel.action"
  connect-timeout-ms: 5000
  read-timeout-ms: 15000